# - name: "Add NodeJS from Nodesource"
#   become: true
#   shell: |
#     curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
#     sudo apt-get install -y nodejs

- name: "Setup NodeJS"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: present
    update_cache: yes

- name: "Setup Pm2 global"
  command: |
    npm install pm2 -g
