---
- name: "create backend project dir "
  file:
    path: /home/ubuntu/backend-project
    state: directory

- name: "unarchive backend packaged folder"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend-project

- name: "setup project dep"
  shell: |
    cd /home/ubuntu/backend-project
    npm install --legacy-peer-deps

- name: "start backend-project with pm2"
  shell: |
    pm2 start main.js
  args:
    chdir: /home/ubuntu/backend-project/dist
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
  register: execute_code

- name: "config pm2 to start as a service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
