---
- name: "create backend project dir "
  file:
    path: ~/backend-app
    state: directory

- name: "unarchive backend packaged folder"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "setup node dep"
  shell: |
    cd ~/backend-app
    npm i

- name: "run backend-app with pm2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

- name: "config pm2 to start as a service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
